"""aktualizacja projektu o rozbicie zamowienien inbound na zamowienie i produkty osobno

Revision ID: 30a0e4a6bc5e
Revises: 93fe1bc0a2cd
Create Date: 2025-10-13 11:31:57.792848

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '30a0e4a6bc5e'
down_revision = '93fe1bc0a2cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inbound_order_products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inbound_order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('net_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inbound_order_id'], ['inbound_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inbound_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warehouse_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('inbound_orders_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'warehouses', ['warehouse_id'], ['id'])
        batch_op.drop_column('product_id')
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inbound_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('inbound_orders_ibfk_1'), 'products', ['product_id'], ['id'])
        batch_op.drop_column('warehouse_id')

    op.drop_table('inbound_order_products')
    # ### end Alembic commands ###
