"""aktualizacja w tabelach

Revision ID: 33cac6d7fd6d
Revises: 6f832efe5f87
Create Date: 2025-10-07 12:33:34.784365

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '33cac6d7fd6d'
down_revision = '6f832efe5f87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inbound_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('CREATED', 'APPROVED', 'PRODUCED', 'IN_TRANSIT', 'DELIVERED', 'COMPLETED', 'CANCELLED', name='inbound_order_status'), nullable=False))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('days_of_dosage', sa.Integer(), nullable=True))

    with op.batch_alter_table('stocks_summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ordered_qty', sa.Integer(), nullable=True))
        batch_op.alter_column('status_of_total_qty',
               existing_type=mysql.ENUM('good_qty', 'medium_qty', 'critical_qty', 'no_products'),
               type_=sa.Enum('GOOD', 'MEDIUM', 'CRITICAL', 'EMPTY', name='stock_qty_status'),
               existing_nullable=False)

    with op.batch_alter_table('stocks_with_exp_dates', schema=None) as batch_op:
        batch_op.alter_column('status_of_exp_date',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('GOOD', 'MEDIUM', 'CRITICAL', 'EXPIRED', 'EMPTY', 'NOT_APPLY', name='exp_date_status'),
               existing_nullable=False)
        batch_op.alter_column('status_of_total_qty',
               existing_type=mysql.ENUM('good_qty', 'medium_qty', 'critical_qty', 'no_products'),
               type_=sa.Enum('GOOD', 'MEDIUM', 'CRITICAL', 'EMPTY', name='stock_qty_status'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks_with_exp_dates', schema=None) as batch_op:
        batch_op.alter_column('status_of_total_qty',
               existing_type=sa.Enum('GOOD', 'MEDIUM', 'CRITICAL', 'EMPTY', name='stock_qty_status'),
               type_=mysql.ENUM('good_qty', 'medium_qty', 'critical_qty', 'no_products'),
               existing_nullable=False)
        batch_op.alter_column('status_of_exp_date',
               existing_type=sa.Enum('GOOD', 'MEDIUM', 'CRITICAL', 'EXPIRED', 'EMPTY', 'NOT_APPLY', name='exp_date_status'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('stocks_summary', schema=None) as batch_op:
        batch_op.alter_column('status_of_total_qty',
               existing_type=sa.Enum('GOOD', 'MEDIUM', 'CRITICAL', 'EMPTY', name='stock_qty_status'),
               type_=mysql.ENUM('good_qty', 'medium_qty', 'critical_qty', 'no_products'),
               existing_nullable=False)
        batch_op.drop_column('ordered_qty')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('days_of_dosage')

    with op.batch_alter_table('inbound_orders', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
