"""Druga tabela suppliers

Revision ID: 533d9499791e
Revises: 746161cd455b
Create Date: 2025-10-06 15:40:26.940682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '533d9499791e'
down_revision = '746161cd455b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.String(length=25), nullable=False),
    sa.Column('ean', sa.String(length=14), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_expiration_date', sa.Boolean(), nullable=False),
    sa.Column('is_dose_product', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ean'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('nip_number', sa.String(length=10), nullable=False),
    sa.Column('country', sa.String(length=255), nullable=False),
    sa.Column('company_address', sa.String(length=255), nullable=False),
    sa.Column('contact_person', sa.String(length=255), nullable=False),
    sa.Column('area_phone_number', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('area_phone_number > 0 and area_phone_number < 999', name='chk_area_phone_number_max_4_positiv_digits'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suppliers')
    op.drop_table('products')
    # ### end Alembic commands ###
