"""Tabela StockwIthExpDates & Stocks_sumamry i zmiany w tabelach 2

Revision ID: 6f832efe5f87
Revises: b2a2bab5488b
Create Date: 2025-10-07 09:21:57.116393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f832efe5f87'
down_revision = 'b2a2bab5488b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks_with_exp_dates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.Column('qty_per_exp_date', sa.Integer(), nullable=True),
    sa.Column('qty_total_of_sku', sa.Integer(), nullable=True),
    sa.Column('status_of_exp_date', sa.String(length=50), nullable=False),
    sa.Column('status_of_total_qty', sa.Enum('good_qty', 'medium_qty', 'critical_qty', 'no_products'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stocks_with_exp_dates')
    # ### end Alembic commands ###
