"""Dodanie numeru telefonu do Supplier

Revision ID: 8d8bbe3dfba7
Revises: 33cac6d7fd6d
Create Date: 2025-10-07 13:57:02.673802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d8bbe3dfba7'
down_revision = '33cac6d7fd6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
