"""nowe tabele arch - przenoszenie arch danych do nowych tabel

Revision ID: 93fe1bc0a2cd
Revises: 8d8bbe3dfba7
Create Date: 2025-10-09 10:34:05.904526

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '93fe1bc0a2cd'
down_revision = '8d8bbe3dfba7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks_summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ordered_in_qty', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
        batch_op.drop_column('ordered_qty')

    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.drop_column('phone_number')

    with op.batch_alter_table('stocks_summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ordered_qty', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('created_at')
        batch_op.drop_column('ordered_in_qty')

    # ### end Alembic commands ###
