"""dodanie tabel Arch

Revision ID: fbcb9e8ef876
Revises: 30a0e4a6bc5e
Create Date: 2025-10-20 13:33:00.284235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbcb9e8ef876'
down_revision = '30a0e4a6bc5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks_summary_arch',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('good_date_qty', sa.Integer(), nullable=True),
    sa.Column('medium_date_qty', sa.Integer(), nullable=True),
    sa.Column('critical_date_qty', sa.Integer(), nullable=True),
    sa.Column('expired_qty', sa.Integer(), nullable=True),
    sa.Column('qty_total_of_sku', sa.Integer(), nullable=True),
    sa.Column('ordered_in_qty', sa.Integer(), nullable=True),
    sa.Column('status_of_total_qty', sa.Enum('GOOD', 'MEDIUM', 'CRITICAL', 'TOO_LOW', 'EMPTY', name='stock_qty_status'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stocks_with_exp_dates_arch',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.Column('qty_per_exp_date', sa.Integer(), nullable=True),
    sa.Column('qty_total_of_sku', sa.Integer(), nullable=True),
    sa.Column('status_of_exp_date', sa.Enum('GOOD', 'MEDIUM', 'CRITICAL', 'EXPIRED', 'EMPTY', 'NOT_APPLY', name='exp_date_status'), nullable=False),
    sa.Column('status_of_total_qty', sa.Enum('GOOD', 'MEDIUM', 'CRITICAL', 'EMPTY', name='stock_qty_status'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stocks_with_exp_dates_arch')
    op.drop_table('stocks_summary_arch')
    # ### end Alembic commands ###
